amazonProperties:
  endpointUrl: https://s3.us-east-3.amazonaws.com
  accessKey: ASIARXRZ2BPB3P45RBMB
  secretKey: LwIViDuWN5fRR4YaVlgKOeuyR8AdgWqXf+wSj7LL
  bucketName: edu.esipe.i3.tpvideoconvertering3s3

pubsub :
  project : videoconvertering3
  topic : tpconverter
aws :
  dynamodb :
    table : table_video
